server:
  port: 8281
spring:
  application:
    name: sbsssmcrud
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://35.79.110.136:5432/shuworld
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 30
      max-lifetime: 1500000
  output:
    ansi:
      enabled: ALWAYS
mybatis:
  configuration:
    lazy-loading-enabled: true
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: jp.co.sony.sbsssmcrud.entity
# DBFile is in the classpath:public/dbfile/world.sql